In [1]:
import os
import pandas as pd

In [2]:
def inspect_data (path, directory):
    
    base_dir = path
    inc_dir = os.path.join(path, directory)
    #print(inc_dir)

    csv_files = [f for f in os.listdir(inc_dir) if f.endswith(".csv")]

    #print(csv_files)

    #rimuovere feature che non hanno senso o di cui abbiamo visto da distribuzione che non danno informazione
    list_columns = list(('Protocollo', 'Gruppo', 'DataOraIncidente', 'Localizzazione1', 'STRADA1',
                        'Localizzazione2', 'STRADA2', 'Chilometrica', 'NaturaIncidente',
                         'particolaritastrade', 'TipoStrada', 'Segnaletica', 'CondizioneAtmosferica',
                         'Traffico', 'Visibilita', 'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI',
                         'Longitude', 'Latitude', 'Progressivo','TipoVeicolo', 'StatoVeicolo', 'TipoPersona',
                         'Sesso', 'Tipolesione', 'Deceduto', 'DecedutoDopo'))
     
    for file in csv_files:
        print("\n"f"FILE: {file}")
        
        file_path = os.path.join(inc_dir, file)
        df = pd.read_csv(file_path, encoding="ISO-8859-1", header=0, delimiter=";")#, usecols = list_columns)
        
        print("\nColonne:")
        print(df.columns.tolist())
        
        #print("\nPrime 5 righe:")
        #display(df.head())
    
        #print("\nUltime 5 righe:")
        #display(df.tail())

In [3]:
base_dir = "/mnt/d/isabe/Desktop/Progetti_ripresa_lavoro/data_2022"
inc_dir = "incidenti/csv"
inspect_data(base_dir, inc_dir)

FILE: incidenti_2022.csv

Colonne:
['Protocollo,Gruppo,DataOraIncidente,Localizzazione1,STRADA1,particolaritastrade,TipoStrada,FondoStradale,Pavimentazione,Segnaletica,Illuminazione,Longitude,Latitude,TipoVeicolo,Sesso,CinturaCascoUtilizzato,Airbag']

FILE: incidenti_2022_01.csv

Colonne:
['Protocollo', 'Gruppo', 'DataOraIncidente', 'Localizzazione1', 'STRADA1', 'Localizzazione2', 'STRADA2', 'Strada02', 'Chilometrica', 'DaSpecificare', 'NaturaIncidente', 'particolaritastrade', 'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'CondizioneAtmosferica', 'Traffico', 'Visibilita', 'Illuminazione', 'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI', 'Longitude', 'Latitude', 'Confermato', 'Progressivo', 'TipoVeicolo', 'StatoVeicolo', 'TipoPersona', 'Sesso', 'Tipolesione', 'Deceduto', 'DecedutoDopo', 'CinturaCascoUtilizzato', 'Airbag', 'Unnamed: 37']

FILE: incidenti_2022_02.csv

Colonne:
['Protocollo', 'Gruppo', 'DataOraIncidente', 'Localizzazione1', 'STRADA1', 'Localizzazione2', 'STRADA2', 'Strada02', 'Chilometrica', 'DaSpecificare', 'NaturaIncidente', 'particolaritastrade', 'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'CondizioneAtmosferica', 'Traffico', 'Visibilita', 'Illuminazione', 'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI', 'Longitude', 'Latitude', 'Confermato', 'Progressivo', 'TipoVeicolo', 'StatoVeicolo', 'TipoPersona', 'Sesso', 'Tipolesione', 'Deceduto', 'DecedutoDopo', 'CinturaCascoUtilizzato', 'Airbag', 'Unnamed: 37']

FILE: incidenti_2022_03.csv

Colonne:
['Protocollo', 'Gruppo', 'DataOraIncidente', 'Localizzazione1', 'STRADA1', 'Localizzazione2', 'STRADA2', 'Strada02', 'Chilometrica', 'DaSpecificare', 'NaturaIncidente', 'particolaritastrade', 'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'CondizioneAtmosferica', 'Traffico', 'Visibilita', 'Illuminazione', 'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI', 'Longitude', 'Latitude', 'Confermato', 'Progressivo', 'TipoVeicolo', 'StatoVeicolo', 'TipoPersona', 'Sesso', 'Tipolesione', 'Deceduto', 'DecedutoDopo', 'CinturaCascoUtilizzato', 'Airbag', 'Unnamed: 37']

FILE: incidenti_2022_04.csv

Colonne:
['Protocollo', 'Gruppo', 'DataOraIncidente', 'Localizzazione1', 'STRADA1', 'Localizzazione2', 'STRADA2', 'Strada02', 'Chilometrica', 'DaSpecificare', 'NaturaIncidente', 'particolaritastrade', 'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'CondizioneAtmosferica', 'Traffico', 'Visibilita', 'Illuminazione', 'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI', 'Longitude', 'Latitude', 'Confermato', 'Progressivo', 'TipoVeicolo', 'StatoVeicolo', 'TipoPersona', 'Sesso', 'Tipolesione', 'Deceduto', 'DecedutoDopo', 'CinturaCascoUtilizzato', 'Airbag', 'Unnamed: 37']

FILE: incidenti_2022_05.csv

Colonne:
['Protocollo', 'Gruppo', 'DataOraIncidente', 'Localizzazione1', 'STRADA1', 'Localizzazione2', 'STRADA2', 'Strada02', 'Chilometrica', 'DaSpecificare', 'NaturaIncidente', 'particolaritastrade', 'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'CondizioneAtmosferica', 'Traffico', 'Visibilita', 'Illuminazione', 'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI', 'Longitude', 'Latitude', 'Confermato', 'Progressivo', 'TipoVeicolo', 'StatoVeicolo', 'TipoPersona', 'Sesso', 'Tipolesione', 'Deceduto', 'DecedutoDopo', 'CinturaCascoUtilizzato', 'Airbag', 'Unnamed: 37']

FILE: incidenti_2022_06.csv

Colonne:
['Protocollo', 'Gruppo', 'DataOraIncidente', 'Localizzazione1', 'STRADA1', 'Localizzazione2', 'STRADA2', 'Strada02', 'Chilometrica', 'DaSpecificare', 'NaturaIncidente', 'particolaritastrade', 'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'CondizioneAtmosferica', 'Traffico', 'Visibilita', 'Illuminazione', 'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI', 'Longitude', 'Latitude', 'Confermato', 'Progressivo', 'TipoVeicolo', 'StatoVeicolo', 'TipoPersona', 'Sesso', 'Tipolesione', 'Deceduto', 'DecedutoDopo', 'CinturaCascoUtilizzato', 'Airbag', 'Unnamed: 37']

FILE: incidenti_2022_07.csv

Colonne:
['Protocollo', 'Gruppo', 'DataOraIncidente', 'Localizzazione1', 'STRADA1', 'Localizzazione2', 'STRADA2', 'Strada02', 'Chilometrica', 'DaSpecificare', 'NaturaIncidente', 'particolaritastrade', 'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'CondizioneAtmosferica', 'Traffico', 'Visibilita', 'Illuminazione', 'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI', 'Longitude', 'Latitude', 'Confermato', 'Progressivo', 'TipoVeicolo', 'StatoVeicolo', 'TipoPersona', 'Sesso', 'Tipolesione', 'Deceduto', 'DecedutoDopo', 'CinturaCascoUtilizzato', 'Airbag', 'Unnamed: 37']

FILE: incidenti_2022_08.csv

Colonne:
['Protocollo', 'Gruppo', 'DataOraIncidente', 'Localizzazione1', 'STRADA1', 'Localizzazione2', 'STRADA2', 'Strada02', 'Chilometrica', 'DaSpecificare', 'NaturaIncidente', 'particolaritastrade', 'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'CondizioneAtmosferica', 'Traffico', 'Visibilita', 'Illuminazione', 'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI', 'Longitude', 'Latitude', 'Confermato', 'Progressivo', 'TipoVeicolo', 'StatoVeicolo', 'TipoPersona', 'Sesso', 'Tipolesione', 'Deceduto', 'DecedutoDopo', 'CinturaCascoUtilizzato', 'Airbag', 'Unnamed: 37']

FILE: incidenti_2022_feature_selected.csv

Colonne:
['Protocollo,Gruppo,DataOraIncidente,Localizzazione1,STRADA1,particolaritastrade,TipoStrada,Segnaletica,Longitude,Latitude,TipoVeicolo,Sesso']

In [9]:
def data_months_check (path, directory):
    base_dir = path
    inc_dir = os.path.join(path, directory)
    print(inc_dir)

    csv_files = [f for f in os.listdir(inc_dir) if f.endswith(".csv")]

    print(csv_files)

    list_columns = list(("Protocollo", "Gruppo", "DataOraIncidente", "Localizzazione1", "STRADA1", 'particolaritastrade',
                         'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'Illuminazione',
                         'Longitude', 'Latitude', 'TipoVeicolo', 'Sesso', 'CinturaCascoUtilizzato', 'Airbag'))
    
    for file in csv_files:
        print("\n"f"FILE: {file}")
        
        file_path = os.path.join(inc_dir, file)
        df = pd.read_csv(file_path, encoding="ISO-8859-1", header=0, delimiter=";", usecols = list_columns)

        df["DataOraIncidente"] = pd.to_datetime(
            df["DataOraIncidente"],
            format="%d/%m/%Y %H:%M:%S",
            errors="coerce"
        )
        df["DataIncidente"] = df["DataOraIncidente"].dt.date
        df["OraIncidente"] = df["DataOraIncidente"].dt.time
    
        #print (df["DataIncidente"].dropna().unique())
    
        mesi_presenti = ( df["DataOraIncidente"] .dropna() .dt.to_period("M") .astype(str) .unique() )
        
        print("\nMesi presenti (YYYY-MM):")
        print(sorted(mesi_presenti))

        #And rename files based on the months

        """
        # Prendiamo la prima data valida
        first_date = df["DataOraIncidente"].dropna().iloc[0]
        
        year = first_date.year
        month = f"{first_date.month:02d}"  # zero-padding
        
        new_name = f"incidenti_{year}_{month}.csv"
        new_path = os.path.join(inc_dir, new_name)
        
        print(f"{file}  →  {new_name}")
        
        os.rename(path, new_path)
        """
        
#print(df.head())

In [10]:
base_dir = "/mnt/d/isabe/Desktop/Progetti_ripresa_lavoro/data_2022"
inc_dir = "incidenti/csv"
data_months_check(base_dir, inc_dir)

/mnt/d/isabe/Desktop/Progetti_ripresa_lavoro/data_2022/incidenti/csv
['incidenti_2022_01.csv', 'incidenti_2022_02.csv', 'incidenti_2022_03.csv', 'incidenti_2022_04.csv', 'incidenti_2022_05.csv', 'incidenti_2022_06.csv', 'incidenti_2022_07.csv', 'incidenti_2022_08.csv']

FILE: incidenti_2022_01.csv

Mesi presenti (YYYY-MM):
['2022-01']

FILE: incidenti_2022_02.csv

Mesi presenti (YYYY-MM):
['2022-02']

FILE: incidenti_2022_03.csv

Mesi presenti (YYYY-MM):
['2022-03']

FILE: incidenti_2022_04.csv

Mesi presenti (YYYY-MM):
['2022-04']

FILE: incidenti_2022_05.csv

Mesi presenti (YYYY-MM):
['2022-05']

FILE: incidenti_2022_06.csv

Mesi presenti (YYYY-MM):
['2022-06']

FILE: incidenti_2022_07.csv

Mesi presenti (YYYY-MM):
['2022-07']

FILE: incidenti_2022_08.csv

Mesi presenti (YYYY-MM):
['2022-08']

In [15]:
#Last function also renames the files. This function would take the renamed files and merge them.
def create_file_by_year (path, directory):
    base_dir = path
    inc_dir = os.path.join(path, directory)
    print(inc_dir)
    
    all_files = sorted([
        f for f in os.listdir(inc_dir)
        if f.startswith("incidenti_2022_") and f.endswith(".csv")
    ])
    print(all_files)

    dfs = []

    #DA AGGIUNGERE IL TARGET!!!!!! NUM FERITI, NUM ILLESI ECC ECC
    list_columns = list(("Protocollo", "Gruppo", "DataOraIncidente", "Localizzazione1", "STRADA1", 'particolaritastrade',
                         'TipoStrada', 'Segnaletica', 'Longitude', 'Latitude',
                         'TipoVeicolo', 'Sesso'))
    
    for file in all_files:
        path = os.path.join(inc_dir, file)
        
        df = pd.read_csv(
            path,
            encoding="ISO-8859-1",
            delimiter=";",
            usecols = list_columns
        )
        
        dfs.append(df)
    
    incidenti_2022 = pd.concat(dfs, ignore_index=True)
    
    output_path = os.path.join(inc_dir, "incidenti_2022_feature_selected.csv")
    incidenti_2022.to_csv(output_path, index=False, encoding="ISO-8859-1")
    
    print("Shape finale:", incidenti_2022.shape)
    display(incidenti_2022.head())
    display(incidenti_2022.tail())

In [16]:
base_dir = "/mnt/d/isabe/Desktop/Progetti_ripresa_lavoro/data_2022"
inc_dir = "incidenti/csv"
create_file_by_year(base_dir, inc_dir)

/mnt/d/isabe/Desktop/Progetti_ripresa_lavoro/data_2022/incidenti/csv
['incidenti_2022_01.csv', 'incidenti_2022_02.csv', 'incidenti_2022_03.csv', 'incidenti_2022_04.csv', 'incidenti_2022_05.csv', 'incidenti_2022_06.csv', 'incidenti_2022_07.csv', 'incidenti_2022_08.csv']
Shape finale: (47055, 12)

,Protocollo,Gruppo,DataOraIncidente,Localizzazione1,STRADA1,particolaritastrade,TipoStrada,Segnaletica,Longitude,Latitude,TipoVeicolo,Sesso
0,5764617,20,01/01/2022 01:50:00,Strada Urbana,VIA DEI DUE PONTI,Rettilineo,Una carreggiata a doppio senso,Verticale ed orizzontale,12.4484,41.9647,Autovettura privata,F
1,5764617,20,01/01/2022 01:50:00,Strada Urbana,VIA DEI DUE PONTI,Rettilineo,Una carreggiata a doppio senso,Verticale ed orizzontale,12.4484,41.9647,Autovettura privata,F
2,5764617,20,01/01/2022 01:50:00,Strada Urbana,VIA DEI DUE PONTI,Rettilineo,Una carreggiata a doppio senso,Verticale ed orizzontale,12.4484,41.9647,Autovettura privata,F
3,5764617,20,01/01/2022 01:50:00,Strada Urbana,VIA DEI DUE PONTI,Rettilineo,Una carreggiata a doppio senso,Verticale ed orizzontale,12.4484,41.9647,Autovettura privata,M
4,5764669,1,01/01/2022 04:10:00,Strada Urbana,VIA DELLE SETTE SALE,Rettilineo,Una carreggiata a senso unico di marcia,Orizzontale,NaN,NaN,Autovettura privata,M

,Protocollo,Gruppo,DataOraIncidente,Localizzazione1,STRADA1,particolaritastrade,TipoStrada,Segnaletica,Longitude,Latitude,TipoVeicolo,Sesso
47050,6121853,19,21/08/2022 06:45:00,NaN,VIA DEI MONTI DI PRIMAVALLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47051,6127240,1,03/08/2022 00:40:00,Strada Urbana,PIAZZA DELL'ESQUILINO,Incrocio,Una carreggiata a doppio senso,Verticale ed orizzontale,12.4972,41.8984,Autovettura privata,M
47052,6127240,1,03/08/2022 00:40:00,Strada Urbana,PIAZZA DELL'ESQUILINO,Incrocio,Una carreggiata a doppio senso,Verticale ed orizzontale,12.4972,41.8984,Autovettura privata,F
47053,6208447,6,30/08/2022 19:30:00,Strada Urbana,VIALE DELLA SERENISSIMA,Rettilineo,Due carreggiate,Verticale ed orizzontale,12.5582,41.8987,NaN,F
47054,6208447,6,30/08/2022 19:30:00,Strada Urbana,VIALE DELLA SERENISSIMA,Rettilineo,Due carreggiate,Verticale ed orizzontale,12.5582,41.8987,Motociclo a solo,NaN