In [1]:
import os
import pandas as pd

In [2]:
def inspect_data (path, directory):
    
    base_dir = path
    inc_dir = os.path.join(path, directory)
    print(inc_dir)

    csv_files = [f for f in os.listdir(inc_dir) if f.endswith(".csv")]

    print(csv_files)

    """
    list_columns = list(("Protocollo", "Gruppo", "DataOraIncidente", "Localizzazione1", "STRADA1", 'particolaritastrade',
                         'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'Illuminazione',
                         'Longitude', 'Latitude', 'TipoVeicolo', 'Sesso', 'CinturaCascoUtilizzato', 'Airbag'))
    """
    
    for file in csv_files:
        print("\n"f"FILE: {file}")
        
        file_path = os.path.join(inc_dir, file)
        df = pd.read_csv(file_path, encoding="ISO-8859-1", header=0, delimiter=";")#, usecols = list_columns)
        #drop all unnamed columns
        df.drop(df.columns[df.columns.str.contains('unnamed', case=False)], axis=1, inplace=True)
        
        print("\nColonne:")
        print(df.columns.tolist())
        
        #print("\nPrime 5 righe:")
        #display(df.head())
    
        #print("\nUltime 5 righe:")
        #display(df.tail())

In [3]:
base_dir = "/mnt/d/isabe/Desktop/Progetti_ripresa_lavoro/data/2022/"
inc_dir = "incidenti/csv"
inspect_data(base_dir, inc_dir)

/mnt/d/isabe/Desktop/Progetti_ripresa_lavoro/data/2022/incidenti/csv
['incidenti_2022_01.csv', 'incidenti_2022_02.csv', 'incidenti_2022_03.csv', 'incidenti_2022_04.csv', 'incidenti_2022_05.csv', 'incidenti_2022_06.csv', 'incidenti_2022_07.csv', 'incidenti_2022_08.csv']

FILE: incidenti_2022_01.csv

Colonne:
['Protocollo', 'Gruppo', 'DataOraIncidente', 'Localizzazione1', 'STRADA1', 'Localizzazione2', 'STRADA2', 'Strada02', 'Chilometrica', 'DaSpecificare', 'NaturaIncidente', 'particolaritastrade', 'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'CondizioneAtmosferica', 'Traffico', 'Visibilita', 'Illuminazione', 'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI', 'Longitude', 'Latitude', 'Confermato', 'Progressivo', 'TipoVeicolo', 'StatoVeicolo', 'TipoPersona', 'Sesso', 'Tipolesione', 'Deceduto', 'DecedutoDopo', 'CinturaCascoUtilizzato', 'Airbag']

FILE: incidenti_2022_02.csv

Colonne:
['Protocollo', 'Gruppo', 'DataOraIncidente', 'Localizzazione1', 'STRADA1', 'Localizzazione2', 'STRADA2', 'Strada02', 'Chilometrica', 'DaSpecificare', 'NaturaIncidente', 'particolaritastrade', 'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'CondizioneAtmosferica', 'Traffico', 'Visibilita', 'Illuminazione', 'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI', 'Longitude', 'Latitude', 'Confermato', 'Progressivo', 'TipoVeicolo', 'StatoVeicolo', 'TipoPersona', 'Sesso', 'Tipolesione', 'Deceduto', 'DecedutoDopo', 'CinturaCascoUtilizzato', 'Airbag']

FILE: incidenti_2022_03.csv

Colonne:
['Protocollo', 'Gruppo', 'DataOraIncidente', 'Localizzazione1', 'STRADA1', 'Localizzazione2', 'STRADA2', 'Strada02', 'Chilometrica', 'DaSpecificare', 'NaturaIncidente', 'particolaritastrade', 'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'CondizioneAtmosferica', 'Traffico', 'Visibilita', 'Illuminazione', 'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI', 'Longitude', 'Latitude', 'Confermato', 'Progressivo', 'TipoVeicolo', 'StatoVeicolo', 'TipoPersona', 'Sesso', 'Tipolesione', 'Deceduto', 'DecedutoDopo', 'CinturaCascoUtilizzato', 'Airbag']

FILE: incidenti_2022_04.csv

Colonne:
['Protocollo', 'Gruppo', 'DataOraIncidente', 'Localizzazione1', 'STRADA1', 'Localizzazione2', 'STRADA2', 'Strada02', 'Chilometrica', 'DaSpecificare', 'NaturaIncidente', 'particolaritastrade', 'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'CondizioneAtmosferica', 'Traffico', 'Visibilita', 'Illuminazione', 'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI', 'Longitude', 'Latitude', 'Confermato', 'Progressivo', 'TipoVeicolo', 'StatoVeicolo', 'TipoPersona', 'Sesso', 'Tipolesione', 'Deceduto', 'DecedutoDopo', 'CinturaCascoUtilizzato', 'Airbag']

FILE: incidenti_2022_05.csv

Colonne:
['Protocollo', 'Gruppo', 'DataOraIncidente', 'Localizzazione1', 'STRADA1', 'Localizzazione2', 'STRADA2', 'Strada02', 'Chilometrica', 'DaSpecificare', 'NaturaIncidente', 'particolaritastrade', 'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'CondizioneAtmosferica', 'Traffico', 'Visibilita', 'Illuminazione', 'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI', 'Longitude', 'Latitude', 'Confermato', 'Progressivo', 'TipoVeicolo', 'StatoVeicolo', 'TipoPersona', 'Sesso', 'Tipolesione', 'Deceduto', 'DecedutoDopo', 'CinturaCascoUtilizzato', 'Airbag']

FILE: incidenti_2022_06.csv

Colonne:
['Protocollo', 'Gruppo', 'DataOraIncidente', 'Localizzazione1', 'STRADA1', 'Localizzazione2', 'STRADA2', 'Strada02', 'Chilometrica', 'DaSpecificare', 'NaturaIncidente', 'particolaritastrade', 'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'CondizioneAtmosferica', 'Traffico', 'Visibilita', 'Illuminazione', 'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI', 'Longitude', 'Latitude', 'Confermato', 'Progressivo', 'TipoVeicolo', 'StatoVeicolo', 'TipoPersona', 'Sesso', 'Tipolesione', 'Deceduto', 'DecedutoDopo', 'CinturaCascoUtilizzato', 'Airbag']

FILE: incidenti_2022_07.csv

Colonne:
['Protocollo', 'Gruppo', 'DataOraIncidente', 'Localizzazione1', 'STRADA1', 'Localizzazione2', 'STRADA2', 'Strada02', 'Chilometrica', 'DaSpecificare', 'NaturaIncidente', 'particolaritastrade', 'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'CondizioneAtmosferica', 'Traffico', 'Visibilita', 'Illuminazione', 'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI', 'Longitude', 'Latitude', 'Confermato', 'Progressivo', 'TipoVeicolo', 'StatoVeicolo', 'TipoPersona', 'Sesso', 'Tipolesione', 'Deceduto', 'DecedutoDopo', 'CinturaCascoUtilizzato', 'Airbag']

FILE: incidenti_2022_08.csv

Colonne:
['Protocollo', 'Gruppo', 'DataOraIncidente', 'Localizzazione1', 'STRADA1', 'Localizzazione2', 'STRADA2', 'Strada02', 'Chilometrica', 'DaSpecificare', 'NaturaIncidente', 'particolaritastrade', 'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'CondizioneAtmosferica', 'Traffico', 'Visibilita', 'Illuminazione', 'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI', 'Longitude', 'Latitude', 'Confermato', 'Progressivo', 'TipoVeicolo', 'StatoVeicolo', 'TipoPersona', 'Sesso', 'Tipolesione', 'Deceduto', 'DecedutoDopo', 'CinturaCascoUtilizzato', 'Airbag']

In [4]:
def data_months_check (path, directory):
    base_dir = path
    inc_dir = os.path.join(path, directory)
    print(inc_dir)

    csv_files = [f for f in os.listdir(inc_dir) if f.endswith(".csv")]

    print(csv_files)

    list_columns = list(("Protocollo", "Gruppo", "DataOraIncidente", "Localizzazione1", "STRADA1", 'particolaritastrade',
                         'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'Illuminazione',
                         'Longitude', 'Latitude', 'TipoVeicolo', 'Sesso', 'CinturaCascoUtilizzato', 'Airbag'))
    
    for file in csv_files:
        print("\n"f"FILE: {file}")
        
        file_path = os.path.join(inc_dir, file)
        df = pd.read_csv(file_path, encoding="ISO-8859-1", header=0, delimiter=";")#, usecols = list_columns)
        df.drop(df.columns[df.columns.str.contains('unnamed', case=False)], axis=1, inplace=True)


        df["DataOraIncidente"] = pd.to_datetime(
            df["DataOraIncidente"],
            format="%d/%m/%Y %H:%M:%S",
            errors="coerce"
        )
        df["DataIncidente"] = df["DataOraIncidente"].dt.date
        df["OraIncidente"] = df["DataOraIncidente"].dt.time
    
        #print (df["DataIncidente"].dropna().unique())
    
        mesi_presenti = ( df["DataOraIncidente"] .dropna() .dt.to_period("M") .astype(str) .unique() )
        
        print("\nMesi presenti (YYYY-MM):")
        print(sorted(mesi_presenti))

        #And rename files based on the months


        print("\nColonne:")
        print(df.columns.tolist())
        
        
        # Prendiamo la prima data valida
        first_date = df["DataOraIncidente"].dropna().iloc[0]
        
        year = first_date.year
        month = f"{first_date.month:02d}"  # zero-padding
        
        new_name = f"incidenti_{year}_{month}.csv"
        new_path = os.path.join(inc_dir, new_name)
        
        print(f"{file}  →  {new_name}")
        
        #os.rename(path, new_path)
        
        
#print(df.head())

In [5]:
base_dir = "/mnt/d/isabe/Desktop/Progetti_ripresa_lavoro/data/2022/"
inc_dir = "incidenti/csv"
data_months_check(base_dir, inc_dir)

/mnt/d/isabe/Desktop/Progetti_ripresa_lavoro/data/2022/incidenti/csv
['incidenti_2022_01.csv', 'incidenti_2022_02.csv', 'incidenti_2022_03.csv', 'incidenti_2022_04.csv', 'incidenti_2022_05.csv', 'incidenti_2022_06.csv', 'incidenti_2022_07.csv', 'incidenti_2022_08.csv']

FILE: incidenti_2022_01.csv

Mesi presenti (YYYY-MM):
['2022-01']

Colonne:
['Protocollo', 'Gruppo', 'DataOraIncidente', 'Localizzazione1', 'STRADA1', 'Localizzazione2', 'STRADA2', 'Strada02', 'Chilometrica', 'DaSpecificare', 'NaturaIncidente', 'particolaritastrade', 'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'CondizioneAtmosferica', 'Traffico', 'Visibilita', 'Illuminazione', 'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI', 'Longitude', 'Latitude', 'Confermato', 'Progressivo', 'TipoVeicolo', 'StatoVeicolo', 'TipoPersona', 'Sesso', 'Tipolesione', 'Deceduto', 'DecedutoDopo', 'CinturaCascoUtilizzato', 'Airbag', 'DataIncidente', 'OraIncidente']
incidenti_2022_01.csv  →  incidenti_2022_01.csv

FILE: incidenti_2022_02.csv

Mesi presenti (YYYY-MM):
['2022-02']

Colonne:
['Protocollo', 'Gruppo', 'DataOraIncidente', 'Localizzazione1', 'STRADA1', 'Localizzazione2', 'STRADA2', 'Strada02', 'Chilometrica', 'DaSpecificare', 'NaturaIncidente', 'particolaritastrade', 'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'CondizioneAtmosferica', 'Traffico', 'Visibilita', 'Illuminazione', 'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI', 'Longitude', 'Latitude', 'Confermato', 'Progressivo', 'TipoVeicolo', 'StatoVeicolo', 'TipoPersona', 'Sesso', 'Tipolesione', 'Deceduto', 'DecedutoDopo', 'CinturaCascoUtilizzato', 'Airbag', 'DataIncidente', 'OraIncidente']
incidenti_2022_02.csv  →  incidenti_2022_02.csv

FILE: incidenti_2022_03.csv

Mesi presenti (YYYY-MM):
['2022-03']

Colonne:
['Protocollo', 'Gruppo', 'DataOraIncidente', 'Localizzazione1', 'STRADA1', 'Localizzazione2', 'STRADA2', 'Strada02', 'Chilometrica', 'DaSpecificare', 'NaturaIncidente', 'particolaritastrade', 'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'CondizioneAtmosferica', 'Traffico', 'Visibilita', 'Illuminazione', 'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI', 'Longitude', 'Latitude', 'Confermato', 'Progressivo', 'TipoVeicolo', 'StatoVeicolo', 'TipoPersona', 'Sesso', 'Tipolesione', 'Deceduto', 'DecedutoDopo', 'CinturaCascoUtilizzato', 'Airbag', 'DataIncidente', 'OraIncidente']
incidenti_2022_03.csv  →  incidenti_2022_03.csv

FILE: incidenti_2022_04.csv

Mesi presenti (YYYY-MM):
['2022-04']

Colonne:
['Protocollo', 'Gruppo', 'DataOraIncidente', 'Localizzazione1', 'STRADA1', 'Localizzazione2', 'STRADA2', 'Strada02', 'Chilometrica', 'DaSpecificare', 'NaturaIncidente', 'particolaritastrade', 'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'CondizioneAtmosferica', 'Traffico', 'Visibilita', 'Illuminazione', 'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI', 'Longitude', 'Latitude', 'Confermato', 'Progressivo', 'TipoVeicolo', 'StatoVeicolo', 'TipoPersona', 'Sesso', 'Tipolesione', 'Deceduto', 'DecedutoDopo', 'CinturaCascoUtilizzato', 'Airbag', 'DataIncidente', 'OraIncidente']
incidenti_2022_04.csv  →  incidenti_2022_04.csv

FILE: incidenti_2022_05.csv

Mesi presenti (YYYY-MM):
['2022-05']

Colonne:
['Protocollo', 'Gruppo', 'DataOraIncidente', 'Localizzazione1', 'STRADA1', 'Localizzazione2', 'STRADA2', 'Strada02', 'Chilometrica', 'DaSpecificare', 'NaturaIncidente', 'particolaritastrade', 'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'CondizioneAtmosferica', 'Traffico', 'Visibilita', 'Illuminazione', 'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI', 'Longitude', 'Latitude', 'Confermato', 'Progressivo', 'TipoVeicolo', 'StatoVeicolo', 'TipoPersona', 'Sesso', 'Tipolesione', 'Deceduto', 'DecedutoDopo', 'CinturaCascoUtilizzato', 'Airbag', 'DataIncidente', 'OraIncidente']
incidenti_2022_05.csv  →  incidenti_2022_05.csv

FILE: incidenti_2022_06.csv

Mesi presenti (YYYY-MM):
['2022-06']

Colonne:
['Protocollo', 'Gruppo', 'DataOraIncidente', 'Localizzazione1', 'STRADA1', 'Localizzazione2', 'STRADA2', 'Strada02', 'Chilometrica', 'DaSpecificare', 'NaturaIncidente', 'particolaritastrade', 'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'CondizioneAtmosferica', 'Traffico', 'Visibilita', 'Illuminazione', 'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI', 'Longitude', 'Latitude', 'Confermato', 'Progressivo', 'TipoVeicolo', 'StatoVeicolo', 'TipoPersona', 'Sesso', 'Tipolesione', 'Deceduto', 'DecedutoDopo', 'CinturaCascoUtilizzato', 'Airbag', 'DataIncidente', 'OraIncidente']
incidenti_2022_06.csv  →  incidenti_2022_06.csv

FILE: incidenti_2022_07.csv

Mesi presenti (YYYY-MM):
['2022-07']

Colonne:
['Protocollo', 'Gruppo', 'DataOraIncidente', 'Localizzazione1', 'STRADA1', 'Localizzazione2', 'STRADA2', 'Strada02', 'Chilometrica', 'DaSpecificare', 'NaturaIncidente', 'particolaritastrade', 'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'CondizioneAtmosferica', 'Traffico', 'Visibilita', 'Illuminazione', 'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI', 'Longitude', 'Latitude', 'Confermato', 'Progressivo', 'TipoVeicolo', 'StatoVeicolo', 'TipoPersona', 'Sesso', 'Tipolesione', 'Deceduto', 'DecedutoDopo', 'CinturaCascoUtilizzato', 'Airbag', 'DataIncidente', 'OraIncidente']
incidenti_2022_07.csv  →  incidenti_2022_07.csv

FILE: incidenti_2022_08.csv

Mesi presenti (YYYY-MM):
['2022-08']

Colonne:
['Protocollo', 'Gruppo', 'DataOraIncidente', 'Localizzazione1', 'STRADA1', 'Localizzazione2', 'STRADA2', 'Strada02', 'Chilometrica', 'DaSpecificare', 'NaturaIncidente', 'particolaritastrade', 'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica', 'CondizioneAtmosferica', 'Traffico', 'Visibilita', 'Illuminazione', 'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI', 'Longitude', 'Latitude', 'Confermato', 'Progressivo', 'TipoVeicolo', 'StatoVeicolo', 'TipoPersona', 'Sesso', 'Tipolesione', 'Deceduto', 'DecedutoDopo', 'CinturaCascoUtilizzato', 'Airbag', 'DataIncidente', 'OraIncidente']
incidenti_2022_08.csv  →  incidenti_2022_08.csv

In [29]:
#Last function also renames the files. This function would take the renamed files and merge them.
def create_file_by_year (path, directory):
    base_dir = path
    inc_dir = os.path.join(path, directory)
    print(inc_dir)
    
    all_files = sorted([
        f for f in os.listdir(inc_dir)
        if f.startswith("incidenti_2022_") and f.endswith(".csv")
    ])
    print(all_files)

    dfs = []

    #Use all the columns that has at least a menaning. The distribution will be check in the feature selection
    list_columns = list(("Protocollo", "Gruppo", "DataOraIncidente", 'particolaritastrade',
                         'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica',
                         'CondizioneAtmosferica', 'Traffico', 'Visibilita', 'Illuminazione',
                         'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI', 'Longitude',
                         'Latitude', 'TipoVeicolo', 'Sesso', 'Deceduto', 'DecedutoDopo', 'CinturaCascoUtilizzato', 'Airbag'))
    
    for file in all_files:
        path = os.path.join(inc_dir, file)
        
        df = pd.read_csv(
            path,
            encoding="ISO-8859-1",
            delimiter=";",
            usecols = list_columns
        )
        #df.drop(df.columns[df.columns.str.contains('unnamed', case=False)], axis=1, inplace=True)
        
        dfs.append(df)
    
    incidenti_2022 = pd.concat(dfs, ignore_index=True)
    
    output_path = os.path.join(inc_dir, "incidenti_2022.csv")
    incidenti_2022.to_csv(output_path, index=False, encoding="ISO-8859-1")
    
    print("Shape finale:", incidenti_2022.shape)
    print(incidenti_2022.columns)
    #display(incidenti_2022.iloc[0:5, 9:-1])
    display(incidenti_2022.head())
    display(incidenti_2022.tail())

In [30]:
base_dir = "/mnt/d/isabe/Desktop/Progetti_ripresa_lavoro/data/2022/"
inc_dir = "incidenti/csv"
create_file_by_year(base_dir, inc_dir)

/mnt/d/isabe/Desktop/Progetti_ripresa_lavoro/data/2022/incidenti/csv
['incidenti_2022_01.csv', 'incidenti_2022_02.csv', 'incidenti_2022_03.csv', 'incidenti_2022_04.csv', 'incidenti_2022_05.csv', 'incidenti_2022_06.csv', 'incidenti_2022_07.csv', 'incidenti_2022_08.csv']
Shape finale: (47055, 24)
Index(['Protocollo', 'Gruppo', 'DataOraIncidente', 'particolaritastrade',
       'TipoStrada', 'FondoStradale', 'Pavimentazione', 'Segnaletica',
       'CondizioneAtmosferica', 'Traffico', 'Visibilita', 'Illuminazione',
       'NUM_FERITI', 'NUM_RISERVATA', 'NUM_MORTI', 'NUM_ILLESI', 'Longitude',
       'Latitude', 'TipoVeicolo', 'Sesso', 'Deceduto', 'DecedutoDopo',
       'CinturaCascoUtilizzato', 'Airbag'],
      dtype='object')

,Protocollo,Gruppo,DataOraIncidente,particolaritastrade,TipoStrada,FondoStradale,Pavimentazione,Segnaletica,CondizioneAtmosferica,Traffico,...,NUM_MORTI,NUM_ILLESI,Longitude,Latitude,TipoVeicolo,Sesso,Deceduto,DecedutoDopo,CinturaCascoUtilizzato,Airbag
0,5764617,20,01/01/2022 01:50:00,Rettilineo,Una carreggiata a doppio senso,Asciutto,Asfaltata,Verticale ed orizzontale,Sereno,Scarso,...,0,4,12.4484,41.9647,Autovettura privata,F,0.0,NaN,Non accertato,NaN
1,5764617,20,01/01/2022 01:50:00,Rettilineo,Una carreggiata a doppio senso,Asciutto,Asfaltata,Verticale ed orizzontale,Sereno,Scarso,...,0,4,12.4484,41.9647,Autovettura privata,F,0.0,NaN,Non accertato,Inesploso
2,5764617,20,01/01/2022 01:50:00,Rettilineo,Una carreggiata a doppio senso,Asciutto,Asfaltata,Verticale ed orizzontale,Sereno,Scarso,...,0,4,12.4484,41.9647,Autovettura privata,F,0.0,NaN,Non accertato,NaN
3,5764617,20,01/01/2022 01:50:00,Rettilineo,Una carreggiata a doppio senso,Asciutto,Asfaltata,Verticale ed orizzontale,Sereno,Scarso,...,0,4,12.4484,41.9647,Autovettura privata,M,0.0,NaN,Non accertato,Inesploso
4,5764669,1,01/01/2022 04:10:00,Rettilineo,Una carreggiata a senso unico di marcia,Asciutto,Asfaltata,Orizzontale,Nebbia,Scarso,...,0,1,NaN,NaN,Autovettura privata,M,0.0,NaN,NaN,NaN

,Protocollo,Gruppo,DataOraIncidente,particolaritastrade,TipoStrada,FondoStradale,Pavimentazione,Segnaletica,CondizioneAtmosferica,Traffico,...,NUM_MORTI,NUM_ILLESI,Longitude,Latitude,TipoVeicolo,Sesso,Deceduto,DecedutoDopo,CinturaCascoUtilizzato,Airbag
47050,6121853,19,21/08/2022 06:45:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47051,6127240,1,03/08/2022 00:40:00,Incrocio,Una carreggiata a doppio senso,Asciutto,Asfaltata,Verticale ed orizzontale,Sereno,Scarso,...,0,2,12.4972,41.8984,Autovettura privata,M,0.0,NaN,Non accertato,NaN
47052,6127240,1,03/08/2022 00:40:00,Incrocio,Una carreggiata a doppio senso,Asciutto,Asfaltata,Verticale ed orizzontale,Sereno,Scarso,...,0,2,12.4972,41.8984,Autovettura privata,F,0.0,NaN,Non accertato,NaN
47053,6208447,6,30/08/2022 19:30:00,Rettilineo,Due carreggiate,Asciutto,Asfaltata,Verticale ed orizzontale,Sereno,Intenso,...,0,0,12.5582,41.8987,NaN,F,0.0,NON DECEDUTO,NaN,NaN
47054,6208447,6,30/08/2022 19:30:00,Rettilineo,Due carreggiate,Asciutto,Asfaltata,Verticale ed orizzontale,Sereno,Intenso,...,0,0,12.5582,41.8987,Motociclo a solo,NaN,NaN,NaN,NaN,NaN